name: stemflow
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  image_picker: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Mynor
      fonts:
        - asset: assets/fonts/Mynor-BlackWideItalic-BF6476b5d4d7da4.otf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/StemFlow.png"